### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by kurumpa** [ivanzusko/ramda#28]
> Ok, so we like sheep. That's all.

Имеется в виду все же "мы любим овец" (как минимум, нету "are" перед "like"). Предлагаю "Ну ми просто любимо овець, ось і все" или "Все просто: ми любимо вівців"

**Comment by ivanzusko** [comment]
@kurumpa дякую, що звернули на це увагу! Думаю Ви маєте рацію. Пропоную `ми любимо вівцю`, адже там, наче, в однині 😃

**Comment by kurumpa** [comment]
@ivanzusko Уверен, они овец любят как животных, а не одну какую-то )) Единственное и множественное число одинаково пишется - "sheep"

**Comment by ivanzusko** [comment]
@kurumpa дякую 👍  Зміню найближчим часом :wink:

**Comment by ivanzusko** [comment]
@kurumpa , що скажете про [таке](https://github.com/ivanzusko/ramda/pull/30)?

**Comment by kurumpa** [comment]
@ivanzusko норм, и спасибо за перевод!
